# Generated by Django 4.2.2 on 2023-06-21 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.CharField(default='DEFAULT VALUE', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='discounted_price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(max_length=400, null=True),
        ),
    ]
